import { Locale } from '@/i18n.config';
import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

export const metadata: Metadata = {
  title: "Product's App",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  return (
    <html lang={locale} dir={locale === 'il' ? 'rtl' : 'ltr'}>
      <body style={{ margin: 0 }}>
        {/* <ModalProvider> */}
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        {/* </ModalProvider> */}
      </body>
    </html>
  );
}
