import { Locale } from '@/i18n.config';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Product's App",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  return (
    <html lang={locale} dir={locale === 'il' ? 'rtl' : 'ltr'}>
      <body>{children}</body>
    </html>
  );
}
